

argobots:
	gcc -Wall -c -fPIC acoilt.c -I/home/adcastel/argobots/include -L/home/adcastel/argobots/lib -labt -DARGOBOTS
	gcc -shared -o libacoilt.so acoilt.o -I/home/adcastel/argobots/include -L/home/adcastel/argobots/lib -labt


