


all:
	/home/adcastel/src/charm/multicore-linux64/bin/charmc -c ct_return_mode.c -lm
	/home/adcastel/src/charm/multicore-linux64/bin/charmc -o ct_return ct_return_mode.o -language converse++
	

info:
	/home/adcastel/src/charm/multicore-linux64/bin/charmc -c ct_return_mode.c -lm -DVERBOSE
	/home/adcastel/src/charm/multicore-linux64/bin/charmc -o ct_return ct_return_mode.o -language converse++


